export const mainTextCharacters = "There are 34 playable characters in The Binding of Isaac: Rebirth, with 11 available in the base game and 23 available in the DLCs. Five of these characters (Isaac, Magdalene, Cain, Judas, and ???) came with the original The Binding of Isaac, while two additional characters (Eve and Samson) were added later. Eve was added in The Binding of Isaac's Halloween Update, while Samson was added in the Wrath of the Lamb expansion. Rebirth contains four new characters (Azazel, Lazarus, Eden, and The Lost). In the Afterbirth expansion, one new character (Lilith) was added, plus one more character via an update (Keeper). In the Afterbirth † expansion, one character (Apollyon) was added, plus one more secret character (The Forgotten) added via a Booster Pack. In the Repentance expansion, two characters (Bethany and Jacob & Esau) were added. Each character starts with different stats and abilities that give them their own unique playstyle. \n Repentance also added an alternate 'tainted' version of all 17 characters, unlockable in the expansion's final endgame area. Each tainted character maintains the same general theme as the original incarnation, but twisted or taken to an extreme. Many have unique, game-changing mechanics, but often come with a corresponding drawback"
export const mainTextItems = "Items are an integral part of the gameplay of The Binding of Isaac: Rebirth. They modify Isaac's attributes, grant or modify tear effects, and much more. \n Items are classified into several distinct types and groups. Some items are passive, which add an effect permanently to Isaac, while others only activate when used. The original The Binding of Isaac had 196 items. Rebirth has a total of 341 items. Afterbirth added 95 new items, for a total of 436 items. Afterbirth † added 111 new items, for a total of 547 items. Repentance added 169 new items, for a total of 716 items. An update for Repentance, V1.7.5, added 3 new items, for a total of 719 items. In Afterbirth † and prior, 13 items are considered special and will be less likely to appear if the player has already come across other special items. The Repentance expansion removed the Special Item mechanic, replacing it with the item weight and item quality mechanics."
export const mainTextPickups = "Pickups are minor items that can be found throughout the game"
export const mainTextAchievements = "Achievements are unlocked after completing Challenges, reaching certain milestones, achieving hidden goals, or unlocking certain items. In the PC version, every Steam achievement exactly corresponds to one secret in-game, whereas only a handful of secrets are represented by PSN trophies in the PlayStation version of the game. \n Rebirth has a total of 178 unlockable secrets. Afterbirth added 98 new secrets, for a total of 276. Afterbirth † added 63 new secrets, for a total of 339. Booster Pack #5 added 64 new secrets, for a total of 403. Repentance added 237 new secrets, for a total of 640."

export const charactersProperties = ["Name", "Image", "Unlock method"]
export const itemsProperties = ["Name", "Image", "Description", "Type"]
export const pickupsProperties = ["Name", "Image", "Description", "Type"]
export const achievementsProperties = ["Name", "Image", "Description", "How to"]

export const charactersPropertiesUserLog = ["Name", "Image", "Unlock method", "Got it?"]
export const achievementsPropertiesUserLog = ["Name", "Image", "Description", "How to", "Got it?"]